#!/bin/sh
# ## Overview
# Generates a customized Vagrantfile pointing to synthesized LibScript .box packages
# supporting VirtualBox, Libvirt, and QEMU providers with automated port forwarding.
#
# ## Usage
# Run `gen_vagrantfile.sh [box_package_or_name] [output_path] [memory_mb] [cpus]`

set -feu

if [ "${SCRIPT_NAME-}" ]; then
  THIS_FILE="${SCRIPT_NAME}"
elif [ "${BASH_SOURCE-}" ]; then
  THIS_FILE="${BASH_SOURCE}"
else
  THIS_FILE="${0}"
fi

case "${STACK+x}" in
  *':'"${THIS_FILE}"':'*)
    printf '[STOP]     processing "%s"
' "${THIS_FILE}" >&2
    if (return 0 2>/dev/null); then return; else exit 0; fi ;;
  *) printf '[CONTINUE] processing "%s"
' "${THIS_FILE}" >&2 ;;
esac
export STACK="${STACK:-}${THIS_FILE}"':'
SCRIPT_DIR=$(cd -- "$(dirname -- "${THIS_FILE}")" && pwd)
: "${LIBSCRIPT_ROOT_DIR:=$(d="$SCRIPT_DIR"; while [ ! -f "$d/libscript.sh" ]; do n="${d%/*}"; [ -z "$n" ] && n="/"; [ "$d" = "$n" ] && break; d="$n"; done; printf '%s
' "$d")}"
export LIBSCRIPT_ROOT_DIR

BOX="${1:-${LIBSCRIPT_ROOT_DIR}/build/libscript.box}"
OUT_FILE="${2:-${LIBSCRIPT_ROOT_DIR}/build/Vagrantfile}"
MEM="${3:-2048}"
CPUS="${4:-2}"

OUT_DIR="${OUT_FILE%/*}"
[ -z "$OUT_DIR" ] || mkdir -p "$OUT_DIR"

printf '[VAGRANT] Generating customized Vagrantfile for box %s -> %s...
' "$BOX" "$OUT_FILE"

cat <<EOF > "$OUT_FILE"
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile generated by LibScript

Vagrant.configure("2") do |config|
  config.vm.box = "${BOX}"
  config.vm.hostname = "libscript-node"

  # Port forwardings
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true

  # VirtualBox Provider
  config.vm.provider "virtualbox" do |vb|
    vb.name = "libscript-vm"
    vb.memory = ${MEM}
    vb.cpus = ${CPUS}
    vb.linked_clone = true
  end

  # Libvirt Provider
  config.vm.provider "libvirt" do |lv|
    lv.memory = ${MEM}
    lv.cpus = ${CPUS}
  end

  # QEMU Provider
  config.vm.provider "qemu" do |qe|
    qe.memory = "${MEM}M"
    qe.smp = "${CPUS}"
  end
end
EOF

printf '[OK] Vagrantfile generated successfully: %s
' "$OUT_FILE"
exit 0
