@echo off
:: # gen_vagrantfile.cmd
::
:: ## Overview
:: Generates a customized Vagrantfile pointing to synthesized LibScript .box packages on Windows.
:: Supports VirtualBox, Hyper-V, and QEMU providers.
::
:: ## Usage
:: gen_vagrantfile.cmd [box_package_or_name] [output_path] [memory_mb] [cpus]

setlocal EnableDelayedExpansion
set "THIS_FILE=%~f0"

SET "searchVal=;%THIS_FILE%;"
IF NOT DEFINED STACK (
    SET "STACK=;%THIS_FILE%;"
    echo [CONTINUE] processing "%THIS_FILE%"
) ELSE (
    IF NOT "!STACK:%searchVal%=!"=="!STACK!" (
        echo [STOP]     processing "%THIS_FILE%"
        SET ERRORLEVEL=0
        goto :eof
    ) ELSE (
        SET "STACK=!STACK!%THIS_FILE%;"
        echo [CONTINUE] processing "%THIS_FILE%"
    )
)

if "%~1"=="--help" (
    echo Usage: %~nx0 [box] [output_path] [memory_mb] [cpus]
    echo Generates customized Vagrantfile.
    exit /b 0
)
if "%~1"=="-h" (
    echo Usage: %~nx0 [box] [output_path] [memory_mb] [cpus]
    echo Generates customized Vagrantfile.
    exit /b 0
)

set "BOX=%~1"
if "%BOX%"=="" set "BOX=libscript.box"
set "OUT_FILE=%~2"
if "%OUT_FILE%"=="" (
    set "SCRIPT_DIR=%~dp0"
    for %%I in ("%SCRIPT_DIR%\..\..\..") do set "REPO_ROOT=%%~fI"
    set "OUT_FILE=!REPO_ROOT!\build\Vagrantfile"
)
set "MEM=%~3"
if "%MEM%"=="" set "MEM=2048"
set "CPUS=%~4"
if "%CPUS%"=="" set "CPUS=2"

for %%I in ("%OUT_FILE%") do set "OUT_DIR=%%~dpI"
if not exist "%OUT_DIR%" mkdir "%OUT_DIR%"

echo [VAGRANT] Generating customized Vagrantfile for %BOX% -^> %OUT_FILE%...

(
    echo # -*- mode: ruby -*-
    echo # vi: set ft=ruby :
    echo # Vagrantfile generated by LibScript
    echo.
    echo Vagrant.configure^("2"^) do ^|config^|
    echo   config.vm.box = "%BOX%"
    echo   config.vm.hostname = "libscript-node"
    echo.
    echo   config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
    echo   config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    echo   config.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true
    echo.
    echo   config.vm.provider "virtualbox" do ^|vb^|
    echo     vb.name = "libscript-vm"
    echo     vb.memory = %MEM%
    echo     vb.cpus = %CPUS%
    echo     vb.linked_clone = true
    echo   end
    echo.
    echo   config.vm.provider "hyperv" do ^|hv^|
    echo     hv.memory = %MEM%
    echo     hv.cpus = %CPUS%
    echo   end
    echo end
) > "%OUT_FILE%"

echo [OK] Vagrantfile generated successfully: %OUT_FILE%
exit /b 0
