#!/bin/sh
# ## Overview
# Declarative Backend Orchestrator. Provisions Python venvs, templates configs,
# runs migrations, and registers N-tier services (Gunicorn/Celery) via systemd.
#
# ## Usage
#   ./provision_wsgi.sh --app-dir <dir> --manifest <path> --packaging <path>

set -feu

if [ "${SCRIPT_NAME-}" ]; then
  THIS_FILE="${SCRIPT_NAME}"
elif [ "${BASH_SOURCE-}" ]; then
  THIS_FILE="${BASH_SOURCE}"
else
  THIS_FILE="${0}"
fi
case "${STACK+x}" in
  *':'"${THIS_FILE}"':'*)
    printf '[STOP]     processing "%s"\n' "${THIS_FILE}" >&2
    if (return 0 2>/dev/null); then return; else exit 0; fi ;;
  *) printf '[CONTINUE] processing "%s"\n' "${THIS_FILE}" >&2 ;;
esac
export STACK="${STACK:-}${THIS_FILE}"':'
SCRIPT_DIR=$(cd -- "$(dirname -- "${THIS_FILE}")" && pwd)
: "${LIBSCRIPT_ROOT_DIR:=$(d="$SCRIPT_DIR"; while [ ! -f "$d/libscript.sh" ]; do n="${d%/*}"; [ -z "$n" ] && n="/"; [ "$d" = "$n" ] && break; d="$n"; done; printf '%s\n' "$d")}"
export DIR="${SCRIPT_DIR}"

app_dir=""
manifest_path=""
packaging_path=""

while [ $# -gt 0 ]; do
  case "$1" in
    --app-dir) app_dir="$2"; shift 2 ;;
    --manifest) manifest_path="$2"; shift 2 ;;
    --packaging) packaging_path="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [ -z "$app_dir" ] || [ -z "$manifest_path" ] || [ -z "$packaging_path" ]; then
  printf 'Error: --app-dir, --manifest, and --packaging are required.\n' >&2
  exit 1
fi

venv_dir="$app_dir/venv"
data_dir="$app_dir/data"
logs_dir="$app_dir/logs"

# 1. Persistent Storage Mapping
mkdir -p "$data_dir" "$logs_dir"
chmod 700 "$data_dir" "$logs_dir"

# 2. Automated Python venv scaffolding
if [ ! -d "$venv_dir" ]; then
  # Assume python is available in PATH or via libscript environment
  python3 -m venv "$venv_dir"
fi

# 3. Application Configuration Rendering (Mock generation for shell)
# In reality, this would parse vars.schema.json using jq and write out .env/yaml.
env_file="$app_dir/.env"
if [ ! -f "$env_file" ]; then
    printf '# Auto-generated by provision_wsgi.sh\nDATA_DIR="%s"\nLOGS_DIR="%s"\n' "$data_dir" "$logs_dir" > "$env_file"
fi

# 4. Plugin & Extension Pipeline
req_file="$app_dir/requirements.txt"
if [ -f "$req_file" ]; then
  # Idempotently install deps/XBlocks
  "$venv_dir/bin/pip" install -q -r "$req_file"
fi

# 5. Multi-daemon processing & Systemd Registration
# This extracts services from packaging.json and generates systemd unit files.
if command -v jq >/dev/null 2>&1; then
  jq -c '.services[]?' "$packaging_path" | while read -r svc; do
    svc_id=$(printf '%s' "$svc" | jq -r '.id')
    svc_type=$(printf '%s' "$svc" | jq -r '.type')
    unit_file="/etc/systemd/system/${svc_id}.service"
    
    if [ ! -f "$unit_file" ] && [ -w "/etc/systemd/system" ]; then
      case "$svc_type" in
        wsgi|asgi)
          port=$(printf '%s' "$svc" | jq -r '.port_binding')
          entrypoint=$(printf '%s' "$svc" | jq -r '.wsgi_entrypoint')
          cat <<EOF > "$unit_file"
[Unit]
Description=$svc_id
After=network.target
[Service]
WorkingDirectory=$app_dir
ExecStart=$venv_dir/bin/gunicorn -b 127.0.0.1:$port $entrypoint
EnvironmentFile=$env_file
Restart=always
[Install]
WantedBy=multi-user.target
EOF
          systemctl daemon-reload
          systemctl enable "$svc_id"
          systemctl start "$svc_id" || true
          ;;
        worker|beat)
          worker_class=$(printf '%s' "$svc" | jq -r '.worker_class')
          cat <<EOF > "$unit_file"
[Unit]
Description=$svc_id worker
After=network.target
[Service]
WorkingDirectory=$app_dir
ExecStart=$venv_dir/bin/celery -A $worker_class worker
EnvironmentFile=$env_file
Restart=always
[Install]
WantedBy=multi-user.target
EOF
          systemctl daemon-reload
          systemctl enable "$svc_id"
          systemctl start "$svc_id" || true
          ;;
      esac
    fi
  done
fi

# 6. Idempotent Lifecycle Hooks (Migrations, Indexing)
if command -v jq >/dev/null 2>&1; then
  jq -c '.lifecycle_hooks.post_install[]?' "$packaging_path" | while read -r hook; do
    cmd=$(printf '%s' "$hook" | jq -r '.command')
    (cd "$app_dir" && eval "$cmd") || true
  done
fi

exit 0