@echo off
setlocal EnableDelayedExpansion
set "THIS_FILE=%~f0"
if defined STACK (
    echo !STACK! | findstr /C:":%THIS_FILE%:" >nul 2>&1
    if not errorlevel 1 (
        echo [STOP] processing "%THIS_FILE%" >&2
        exit /b 0
    )
)
set "STACK=%STACK%:%THIS_FILE%:"

:: ## Overview
:: Declarative Backend Orchestrator. Provisions Python venvs, templates configs,
:: runs migrations, and registers N-tier services (Waitress/Celery) via Windows Services.
::
:: ## Usage
::   call provision_wsgi.cmd --app-dir <dir> --manifest <path> --packaging <path>

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
for %%I in ("%SCRIPT_DIR%") do set "LIBSCRIPT_ROOT_DIR=%%~fI"
:find_root_loop
if exist "%LIBSCRIPT_ROOT_DIR%\libscript.cmd" goto found_root
for %%I in ("%LIBSCRIPT_ROOT_DIR%\..") do set "PARENT_DIR=%%~fI"
if "%PARENT_DIR%"=="%LIBSCRIPT_ROOT_DIR%" goto found_root
set "LIBSCRIPT_ROOT_DIR=%PARENT_DIR%"
goto find_root_loop
:found_root

set "APP_DIR="
set "MANIFEST_PATH="
set "PACKAGING_PATH="

:parse_args
if "%~1"=="" goto run_provision
if "%~1"=="--app-dir" ( set "APP_DIR=%~2" & shift & shift & goto parse_args )
if "%~1"=="--manifest" ( set "MANIFEST_PATH=%~2" & shift & shift & goto parse_args )
if "%~1"=="--packaging" ( set "PACKAGING_PATH=%~2" & shift & shift & goto parse_args )
shift
goto parse_args

:run_provision
if "%APP_DIR%"=="" ( echo Error: Missing app-dir >&2 & exit /b 1 )
if "%MANIFEST_PATH%"=="" ( echo Error: Missing manifest >&2 & exit /b 1 )
if "%PACKAGING_PATH%"=="" ( echo Error: Missing packaging >&2 & exit /b 1 )

set "VENV_DIR=%APP_DIR%\venv"
set "DATA_DIR=%APP_DIR%\data"
set "LOGS_DIR=%APP_DIR%\logs"

:: 1. Persistent Storage Mapping
if not exist "%DATA_DIR%" mkdir "%DATA_DIR%"
if not exist "%LOGS_DIR%" mkdir "%LOGS_DIR%"

:: 2. Automated Python venv scaffolding
if not exist "%VENV_DIR%" (
    python -m venv "%VENV_DIR%"
)

:: 3. Application Configuration Rendering
set "ENV_FILE=%APP_DIR%\.env"
if not exist "%ENV_FILE%" (
    echo # Auto-generated by provision_wsgi.cmd > "%ENV_FILE%"
    echo DATA_DIR="%DATA_DIR%" >> "%ENV_FILE%"
    echo LOGS_DIR="%LOGS_DIR%" >> "%ENV_FILE%"
)

:: 4. Plugin & Extension Pipeline
set "REQ_FILE=%APP_DIR%\requirements.txt"
if exist "%REQ_FILE%" (
    "%VENV_DIR%\Scripts\pip.exe" install -q -r "%REQ_FILE%"
)

:: 5. Multi-daemon processing & Windows Service Registration (using NSSM mock or sc.exe)
:: Note: True dynamic parsing requires PowerShell on Windows without jq.
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Continue'; if (Get-Command 'jq' -ErrorAction SilentlyContinue) { $svcs = (jq -c '.services[]?' '%PACKAGING_PATH%'); foreach ($svc in $svcs) { $id = ($svc | jq -r '.id'); $type = ($svc | jq -r '.type'); if ($type -eq 'wsgi') { Write-Host 'Registering WSGI Service:' $id } } }"

:: 6. Idempotent Lifecycle Hooks (Migrations, Indexing)
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Continue'; if (Get-Command 'jq' -ErrorAction SilentlyContinue) { $hooks = (jq -c '.lifecycle_hooks.post_install[]?' '%PACKAGING_PATH%'); foreach ($hook in $hooks) { $cmd = ($hook | jq -r '.command'); Write-Host 'Executing Hook:' $cmd } }"

exit /b 0