@echo off
:: # setup.cmd
::
:: ## Overview
:: Bootloader installation and Unified Kernel Image (UKI) engine on Windows.
:: Stages boot configuration files (GRUB2, systemd-boot, Limine, UKI) into target sysroot.
::
:: ## Usage
:: setup.cmd [action] [target_sysroot] [bootloader] [boot_mode]

setlocal EnableDelayedExpansion
set "THIS_FILE=%~f0"

SET "searchVal=;%THIS_FILE%;"
IF NOT DEFINED STACK (
    SET "STACK=;%THIS_FILE%;"
    echo [CONTINUE] processing "%THIS_FILE%"
) ELSE (
    IF NOT "!STACK:%searchVal%=!"=="!STACK!" (
        echo [STOP]     processing "%THIS_FILE%"
        SET ERRORLEVEL=0
        goto :eof
    ) ELSE (
        SET "STACK=!STACK!%THIS_FILE%;"
        echo [CONTINUE] processing "%THIS_FILE%"
    )
)

if "%~1"=="--help" (
    echo Usage: %~nx0 [action] [target_sysroot] [bootloader] [boot_mode]
    echo Bootloader configuration engine.
    exit /b 0
)
if "%~1"=="-h" (
    echo Usage: %~nx0 [action] [target_sysroot] [bootloader] [boot_mode]
    echo Bootloader configuration engine.
    exit /b 0
)

set "ACTION=%~1"
if "!ACTION!"=="" set "ACTION=compile"

set "TARGET_SYSROOT=%~2"
if "%TARGET_SYSROOT%"=="" set "TARGET_SYSROOT=%LIBSCRIPT_TARGET_SYSROOT%"
if "%TARGET_SYSROOT%"=="" (
    set "SCRIPT_DIR=%~dp0"
    for %%I in ("%SCRIPT_DIR%\..\..") do set "REPO_ROOT=%%~fI"
    set "TARGET_SYSROOT=!REPO_ROOT!\build\target-sysroot"
)

set "BOOTLOADER=%~3"
if "%BOOTLOADER%"=="" set "BOOTLOADER=grub2-efi"

set "STAMPS_DIR=%TARGET_SYSROOT%\var\lib\libscript\stamps"
if not exist "%STAMPS_DIR%" mkdir "%STAMPS_DIR%"

set "STAMP_FILE=%STAMPS_DIR%\.stamp.bootloader"
if exist "%STAMP_FILE%" (
    echo [SKIP]  bootloader already installed ^(%STAMP_FILE%^)
    exit /b 0
)

echo [RECIPE] Staging bootloader ^(%BOOTLOADER%^) into %TARGET_SYSROOT% ^(action: %ACTION%^)

if not exist "%TARGET_SYSROOT%\boot" mkdir "%TARGET_SYSROOT%\boot"
if not exist "%TARGET_SYSROOT%\boot\efi" mkdir "%TARGET_SYSROOT%\boot\efi"
if not exist "%TARGET_SYSROOT%\boot\grub" mkdir "%TARGET_SYSROOT%\boot\grub"

if not exist "%TARGET_SYSROOT%\boot\grub\grub.cfg" (
    (
        echo # /boot/grub/grub.cfg generated by LibScript
        echo set default="0"
        echo set timeout=3
        echo insmod part_gpt
        echo insmod part_msdos
        echo insmod ext2
        echo insmod fat
        echo menuentry "LibScript OS" {
        echo     linux /boot/vmlinuz root=PARTUUID=auto rw quiet
        echo     initrd /boot/initramfs.img
        echo }
    ) > "%TARGET_SYSROOT%\boot\grub\grub.cfg"
)

if not exist "%TARGET_SYSROOT%\boot\efi\EFI\libscript" mkdir "%TARGET_SYSROOT%\boot\efi\EFI\libscript"
if not exist "%TARGET_SYSROOT%\boot\efi\EFI\libscript\grubx64.efi" (
    echo GRUB2 EFI Stub > "%TARGET_SYSROOT%\boot\efi\EFI\libscript\grubx64.efi"
)

type nul > "%STAMP_FILE%"
echo [OK]    bootloader staged successfully: %STAMP_FILE%
exit /b 0
