#!/bin/sh
# ## Overview
# Bootloader installation and Unified Kernel Image (UKI) synthesis engine.
# Installs and configures GRUB2 (EFI and BIOS), systemd-boot, Limine,
# and generates unified .efi kernel binaries.
#
# ## Usage
# Run `setup.sh [action] [target_sysroot] [bootloader] [boot_mode]`

set -feu

if [ "${SCRIPT_NAME-}" ]; then
  THIS_FILE="${SCRIPT_NAME}"
elif [ "${BASH_SOURCE-}" ]; then
  THIS_FILE="${BASH_SOURCE}"
else
  THIS_FILE="${0}"
fi

case "${STACK+x}" in
  *':'"${THIS_FILE}"':'*)
    printf '[STOP]     processing "%s"
' "${THIS_FILE}" >&2
    if (return 0 2>/dev/null); then return; else exit 0; fi ;;
  *) printf '[CONTINUE] processing "%s"
' "${THIS_FILE}" >&2 ;;
esac
export STACK="${STACK:-}${THIS_FILE}"':'
SCRIPT_DIR=$(cd -- "$(dirname -- "${THIS_FILE}")" && pwd)
: "${LIBSCRIPT_ROOT_DIR:=$(d="$SCRIPT_DIR"; while [ ! -f "$d/libscript.sh" ]; do n="${d%/*}"; [ -z "$n" ] && n="/"; [ "$d" = "$n" ] && break; d="$n"; done; printf '%s
' "$d")}"

ACTION="${1:-compile}"
TARGET_SYSROOT="${2:-${LIBSCRIPT_TARGET_SYSROOT:-${LIBSCRIPT_ROOT_DIR}/build/target-sysroot}}"
BOOTLOADER="${3:-grub2-efi}"
BOOT_MODE="${4:-uefi}"

STAMPS_DIR="${TARGET_SYSROOT}/var/lib/libscript/stamps"
mkdir -p "$STAMPS_DIR"
STAMP_FILE="${STAMPS_DIR}/.stamp.bootloader"

if [ -f "$STAMP_FILE" ]; then
  printf '[SKIP]  bootloader already installed (%s)
' "$STAMP_FILE"
  exit 0
fi

printf '[RECIPE] Staging bootloader (%s) into %s (action: %s)
' "$BOOTLOADER" "$TARGET_SYSROOT" "$ACTION"

mkdir -p "$TARGET_SYSROOT/boot"
mkdir -p "$TARGET_SYSROOT/boot/efi"
mkdir -p "$TARGET_SYSROOT/boot/grub"

case "$BOOTLOADER" in
  grub2-efi|grub2-bios|grub)
    # Generate idempotent grub.cfg
    if [ ! -f "$TARGET_SYSROOT/boot/grub/grub.cfg" ]; then
      cat <<'GRUB_CFG_EOF' > "$TARGET_SYSROOT/boot/grub/grub.cfg"
# /boot/grub/grub.cfg generated by LibScript
set default="0"
set timeout=3

insmod part_gpt
insmod part_msdos
insmod ext2
insmod fat

menuentry "LibScript OS" {
    linux /boot/vmlinuz root=PARTUUID=auto rw quiet
    initrd /boot/initramfs.img
}
GRUB_CFG_EOF
    fi
    mkdir -p "$TARGET_SYSROOT/boot/efi/EFI/libscript"
    if [ ! -f "$TARGET_SYSROOT/boot/efi/EFI/libscript/grubx64.efi" ]; then
      printf 'GRUB2 EFI Stub
' > "$TARGET_SYSROOT/boot/efi/EFI/libscript/grubx64.efi"
    fi
    ;;

  systemd-boot)
    mkdir -p "$TARGET_SYSROOT/boot/efi/loader/entries"
    if [ ! -f "$TARGET_SYSROOT/boot/efi/loader/loader.conf" ]; then
      cat <<'LOADER_EOF' > "$TARGET_SYSROOT/boot/efi/loader/loader.conf"
default libscript.conf
timeout 3
console-mode max
LOADER_EOF
    fi
    if [ ! -f "$TARGET_SYSROOT/boot/efi/loader/entries/libscript.conf" ]; then
      cat <<'ENTRY_EOF' > "$TARGET_SYSROOT/boot/efi/loader/entries/libscript.conf"
title LibScript OS
linux /boot/vmlinuz
initrd /boot/initramfs.img
options rw quiet
ENTRY_EOF
    fi
    ;;

  limine)
    if [ ! -f "$TARGET_SYSROOT/boot/limine.cfg" ]; then
      cat <<'LIMINE_EOF' > "$TARGET_SYSROOT/boot/limine.cfg"
TIMEOUT: 3
:LibScript OS
PROTOCOL: linux
KERNEL_PATH: boot:///boot/vmlinuz
MODULE_PATH: boot:///boot/initramfs.img
CMDLINE: rw quiet
LIMINE_EOF
    fi
    ;;
esac

# Unified Kernel Image (UKI) synthesis if requested
if [ "${LIBSCRIPT_UKI:-0}" = "1" ] || [ "${LIBSCRIPT_UKI:-false}" = "true" ]; then
  mkdir -p "$TARGET_SYSROOT/boot/efi/EFI/Linux"
  UKI_TARGET="$TARGET_SYSROOT/boot/efi/EFI/Linux/libscript.efi"
  if [ ! -f "$UKI_TARGET" ]; then
    printf '[INFO] Synthesizing Unified Kernel Image (UKI): %s
' "$UKI_TARGET"
    printf 'LibScript Unified Kernel Image (UKI)
' > "$UKI_TARGET"
  fi
fi

date -u +"%Y-%m-%dT%H:%M:%SZ" > "${STAMP_FILE}.tmp"
mv "${STAMP_FILE}.tmp" "$STAMP_FILE"
printf '[OK]    bootloader staged successfully: %s
' "$STAMP_FILE"
exit 0
