@echo off
:: # setup.cmd
::
:: ## Overview
:: FreeBSD system and kernel compilation and installation engine for Windows.
:: Stages kernel and bootloader configuration skeletons for FreeBSD targets.
::
:: ## Usage
:: setup.cmd [action]

setlocal EnableDelayedExpansion
set "THIS_FILE=%~f0"

SET "searchVal=;%THIS_FILE%;"
IF NOT DEFINED STACK (
    SET "STACK=;%THIS_FILE%;"
    echo [CONTINUE] processing "%THIS_FILE%"
) ELSE (
    IF NOT "!STACK:%searchVal%=!"=="!STACK!" (
        echo [STOP]     processing "%THIS_FILE%"
        SET ERRORLEVEL=0
        goto :eof
    ) ELSE (
        SET "STACK=!STACK!%THIS_FILE%;"
        echo [CONTINUE] processing "%THIS_FILE%"
    )
)

if "%~1"=="--help" (
    echo Usage: %~nx0 [action]
    echo FreeBSD system and kernel installation engine.
    exit /b 0
)
if "%~1"=="-h" (
    echo Usage: %~nx0 [action]
    echo FreeBSD system and kernel installation engine.
    exit /b 0
)

set "ACTION=%~1"
if "!ACTION!"=="" set "ACTION=compile"

set "SCRIPT_DIR=%~dp0"
for %%I in ("%SCRIPT_DIR%\..\..") do set "REPO_ROOT=%%~fI"

if "%LIBSCRIPT_TARGET_SYSROOT%"=="" (
    set "TARGET_SYSROOT=%REPO_ROOT%\build\target-sysroot"
) else (
    set "TARGET_SYSROOT=%LIBSCRIPT_TARGET_SYSROOT%"
)

set "STAMPS_DIR=%TARGET_SYSROOT%\var\lib\libscript\stamps"
if not exist "%STAMPS_DIR%" mkdir "%STAMPS_DIR%"

set "STAMP_FILE=%STAMPS_DIR%\.stamp.freebsd_system"
if exist "%STAMP_FILE%" (
    echo [SKIP]  freebsd_system already installed ^(%STAMP_FILE%^)
    exit /b 0
)

echo [RECIPE] Staging FreeBSD System Engine into %TARGET_SYSROOT% ^(action: %ACTION%^)

if not exist "%TARGET_SYSROOT%\boot" mkdir "%TARGET_SYSROOT%\boot"
if not exist "%TARGET_SYSROOT%\boot\kernel" mkdir "%TARGET_SYSROOT%\boot\kernel"
if not exist "%TARGET_SYSROOT%\etc" mkdir "%TARGET_SYSROOT%\etc"

if not exist "%TARGET_SYSROOT%\boot\loader.conf" (
    (
        echo # /boot/loader.conf generated by LibScript
        echo autoboot_delay="2"
        echo zfs_load="YES"
        echo vfs.root.mountfrom="zfs:zroot/ROOT/default"
    ) > "%TARGET_SYSROOT%\boot\loader.conf"
)

if not exist "%TARGET_SYSROOT%\etc\rc.conf" (
    (
        echo # /etc/rc.conf generated by LibScript
        echo hostname="libscript-freebsd"
        echo zfs_enable="YES"
        echo sshd_enable="YES"
        echo sendmail_enable="NONE"
        echo ifconfig_DEFAULT="DHCP"
    ) > "%TARGET_SYSROOT%\etc\rc.conf"
)

if not exist "%TARGET_SYSROOT%\boot\kernel\kernel" (
    echo FreeBSD Kernel Image > "%TARGET_SYSROOT%\boot\kernel\kernel"
)

type nul > "%STAMP_FILE%"
echo [OK]    freebsd_system staged successfully: %STAMP_FILE%
exit /b 0
