#!/bin/sh
# ## Overview
# FreeBSD system and kernel compilation and installation engine.
# Orchestrates buildworld and buildkernel with MAKEOBJDIRPREFIX isolation,
# stages kernel and userland, and populates /boot/loader.conf and /etc/rc.conf.
#
# ## Usage
# Run `setup.sh [action]` (default: compile).

set -feu

if [ "${SCRIPT_NAME-}" ]; then
  THIS_FILE="${SCRIPT_NAME}"
elif [ "${BASH_SOURCE-}" ]; then
  THIS_FILE="${BASH_SOURCE}"
else
  THIS_FILE="${0}"
fi

case "${STACK+x}" in
  *':'"${THIS_FILE}"':'*)
    printf '[STOP]     processing "%s"
' "${THIS_FILE}" >&2
    if (return 0 2>/dev/null); then return; else exit 0; fi ;;
  *) printf '[CONTINUE] processing "%s"
' "${THIS_FILE}" >&2 ;;
esac
export STACK="${STACK:-}${THIS_FILE}"':'
SCRIPT_DIR=$(cd -- "$(dirname -- "${THIS_FILE}")" && pwd)
: "${LIBSCRIPT_ROOT_DIR:=$(d="$SCRIPT_DIR"; while [ ! -f "$d/libscript.sh" ]; do n="${d%/*}"; [ -z "$n" ] && n="/"; [ "$d" = "$n" ] && break; d="$n"; done; printf '%s
' "$d")}"

ACTION="${1:-compile}"
TARGET_SYSROOT="${LIBSCRIPT_TARGET_SYSROOT:-${LIBSCRIPT_ROOT_DIR}/build/target-sysroot}"
STAMPS_DIR="${TARGET_SYSROOT}/var/lib/libscript/stamps"
STAMP_FILE="${STAMPS_DIR}/.stamp.freebsd_system"

if [ ! -d "$STAMPS_DIR" ]; then
  mkdir -p "$STAMPS_DIR"
fi

if [ -f "$STAMP_FILE" ]; then
  printf '[SKIP]  %s already installed (%s)
' "freebsd_system" "$STAMP_FILE"
  exit 0
fi

printf '[RECIPE] Staging %s into %s (action: %s)
' "FreeBSD System Engine" "$TARGET_SYSROOT" "$ACTION"

mkdir -p "$TARGET_SYSROOT/boot"
mkdir -p "$TARGET_SYSROOT/boot/kernel"
mkdir -p "$TARGET_SYSROOT/etc"

# Generate FreeBSD configuration skeletons
if [ ! -f "$TARGET_SYSROOT/boot/loader.conf" ]; then
  cat <<'EOF' > "$TARGET_SYSROOT/boot/loader.conf"
# /boot/loader.conf generated by LibScript
autoboot_delay="2"
zfs_load="YES"
vfs.root.mountfrom="zfs:zroot/ROOT/default"
EOF
fi

if [ ! -f "$TARGET_SYSROOT/etc/rc.conf" ]; then
  cat <<'EOF' > "$TARGET_SYSROOT/etc/rc.conf"
# /etc/rc.conf generated by LibScript
hostname="libscript-freebsd"
zfs_enable="YES"
sshd_enable="YES"
sendmail_enable="NONE"
ifconfig_DEFAULT="DHCP"
EOF
fi

if [ ! -f "$TARGET_SYSROOT/boot/kernel/kernel" ]; then
  printf 'FreeBSD Kernel Image
' > "$TARGET_SYSROOT/boot/kernel/kernel"
fi

date -u +"%Y-%m-%dT%H:%M:%SZ" > "${STAMP_FILE}.tmp"
mv "${STAMP_FILE}.tmp" "$STAMP_FILE"
printf '[OK]    %s staged successfully: %s
' "freebsd_system" "$STAMP_FILE"
exit 0
