#!/bin/sh
# ## Overview
# Formats target partitions (ext4, btrfs, xfs, vfat) and generates
# persistent /etc/fstab configuration with idempotency checks.
#
# ## Usage
# Execute with target device and filesystem type:
#   ./_lib/storage/format_fs.sh <block_device_or_image> [fs_type] [mount_point]

set -feu
if [ "${SCRIPT_NAME-}" ]; then
  THIS_FILE="${SCRIPT_NAME}"
elif [ "${BASH_SOURCE-}" ]; then
  THIS_FILE="${BASH_SOURCE}"
else
  THIS_FILE="${0}"
fi

case "${STACK+x}" in
  *':'"${THIS_FILE}"':'*)
    printf '[STOP]     processing "%s"
' "${THIS_FILE}" >&2
    if (return 0 2>/dev/null); then return; else exit 0; fi ;;
  *) printf '[CONTINUE] processing "%s"
' "${THIS_FILE}" >&2 ;;
esac
export STACK="${STACK:-}${THIS_FILE}"':'
SCRIPT_DIR=$(cd -- "$(dirname -- "${THIS_FILE}")" && pwd)
: "${LIBSCRIPT_ROOT_DIR:=$(d="$SCRIPT_DIR"; while [ ! -f "$d/libscript.sh" ]; do n="${d%/*}"; [ -z "$n" ] && n="/"; [ "$d" = "$n" ] && break; d="$n"; done; printf '%s
' "$d")}"
export LIBSCRIPT_ROOT_DIR

DEV_PATH="${1:-}"
FS_TYPE="${2:-ext4}"
MOUNT_POINT="${3:-/}"

if [ -z "$DEV_PATH" ]; then
  printf '[ERROR] Target device or partition path required.
' >&2
  printf 'Usage: %s <block_device_or_image> [fs_type] [mount_point]
' "$THIS_FILE" >&2
  exit 1
fi

# Idempotency: check blkid
existing_fs=""
if command -v blkid >/dev/null 2>&1; then
  existing_fs=$(blkid -s TYPE -o value "$DEV_PATH" 2>/dev/null || true)
fi

if [ -n "$existing_fs" ]; then
  printf '[INFO] Device %s already formatted as %s. Skipping.
' "$DEV_PATH" "$existing_fs"
  exit 0
fi

printf '[INFO] Formatting %s as %s...\n' "$DEV_PATH" "$FS_TYPE"
case "$FS_TYPE" in
  ext4)
    mkfs.ext4 -F "$DEV_PATH"
    ;;
  btrfs)
    mkfs.btrfs -f "$DEV_PATH"
    ;;
  xfs)
    mkfs.xfs -f "$DEV_PATH"
    ;;
  vfat|fat32)
    mkfs.vfat -F32 "$DEV_PATH"
    ;;
  zfs)
    if command -v zpool >/dev/null 2>&1; then
      zpool create -f -o ashift=12 -O compression=lz4 -O acltype=posixacl -O xattr=sa -O normalization=formD -R "$MOUNT_POINT" zroot "$DEV_PATH" 2>/dev/null || true
    fi
    ;;
  *)
    printf '[ERROR] Unsupported filesystem type: %s\n' "$FS_TYPE" >&2
    exit 1
    ;;
esac

# 2. Sysroot population via rsync if source sysroot provided
SRC_SYSROOT="${4:-${LIBSCRIPT_TARGET_SYSROOT:-}}"
if [ -n "$SRC_SYSROOT" ] && [ -d "$SRC_SYSROOT" ] && [ "$MOUNT_POINT" != "/" ] && [ -d "$MOUNT_POINT" ]; then
  if command -v rsync >/dev/null 2>&1; then
    printf '[INFO] Populating sysroot into %s via rsync...\n' "$MOUNT_POINT"
    rsync -aHAX --quiet "$SRC_SYSROOT/" "$MOUNT_POINT/" 2>/dev/null || cp -a "$SRC_SYSROOT/." "$MOUNT_POINT/" 2>/dev/null || true
  fi
fi

# 3. Persistent /etc/fstab generation using blkid UUID
if [ -d "$MOUNT_POINT/etc" ] && command -v blkid >/dev/null 2>&1; then
  PART_UUID=$(blkid -s UUID -o value "$DEV_PATH" 2>/dev/null || true)
  if [ -n "$PART_UUID" ]; then
    mkdir -p "$MOUNT_POINT/etc"
    if [ ! -f "$MOUNT_POINT/etc/fstab" ]; then
      cat <<EOF > "$MOUNT_POINT/etc/fstab"
# /etc/fstab generated by LibScript
UUID=${PART_UUID}  /  ${FS_TYPE}  defaults,noatime  0  1
tmpfs  /tmp  tmpfs  defaults,nosuid,nodev,mode=1777  0  0
EOF
    fi
  fi
fi

printf '[INFO] Filesystem format completed: %s (%s)\n' "$DEV_PATH" "$FS_TYPE"
exit 0
