#!/bin/sh
# ## Overview
# Configures modular init system supervision inside illumos target sysroot.
# Supports native SMF (Service Management Facility), runit, s6, dinit, and inittab-sysv,
# staging service definitions, SMF site profiles, and loader init paths.
#
# ## Usage
# Configure init system:
#   _lib/illumos/distro/init.sh [sysroot_path] [provider] [services_list] [milestone]

set -feu

if [ "${SCRIPT_NAME-}" ]; then
  THIS_FILE="${SCRIPT_NAME}"
elif [ "${BASH_SOURCE-}" ]; then
  THIS_FILE="${BASH_SOURCE}"
else
  THIS_FILE="${0}"
fi

case "${STACK+x}" in
  *':'"${THIS_FILE}"':'*)
    printf '[STOP]     processing "%s"
' "${THIS_FILE}" >&2
    if (return 0 2>/dev/null); then return; else exit 0; fi ;;
  *) printf '[CONTINUE] processing "%s"
' "${THIS_FILE}" >&2 ;;
esac
export STACK="${STACK:-}${THIS_FILE}"':'
SCRIPT_DIR=$(cd -- "$(dirname -- "${THIS_FILE}")" && pwd)
: "${LIBSCRIPT_ROOT_DIR:=$(d="$SCRIPT_DIR"; while [ ! -f "$d/libscript.sh" ]; do n="${d%/*}"; [ -z "$n" ] && n="/"; [ "$d" = "$n" ] && break; d="$n"; done; printf '%s
' "$d")}"
REPO_ROOT="${LIBSCRIPT_ROOT_DIR}"

SYSROOT="${1:-${LIBSCRIPT_TARGET_SYSROOT:-${REPO_ROOT}/build/illumos-sysroot}}"
PROVIDER="${2:-smf}"
SERVICES="${3:-svc:/network/ssh:default,svc:/system/cron:default,svc:/system/system-log:default}"
MILESTONE="${4:-svc:/milestone/multi-user-server:default}"

STAMP_DIR="${SYSROOT}/.libscript_stamps"
STAMP_FILE="${STAMP_DIR}/init_${PROVIDER}.stamp"

mkdir -p "${STAMP_DIR}"
mkdir -p "${SYSROOT}/etc"
mkdir -p "${SYSROOT}/boot"

if [ -f "${STAMP_FILE}" ]; then
  printf '[SKIP]     illumos init system %s already configured in %s
' "${PROVIDER}" "${SYSROOT}"
  exit 0
fi

printf '[INIT]     Configuring illumos init provider %s...
' "${PROVIDER}"

case "${PROVIDER}" in
  smf)
    # Native Solaris / illumos Service Management Facility
    mkdir -p "${SYSROOT}/lib/svc/manifest" "${SYSROOT}/etc/svc/profile"
    cat << EOF > "${SYSROOT}/etc/svc/profile/site.xml"
<?xml version='1.0'?>
<!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
<service_bundle type='profile' name='site'>
  <!-- Site customization profile generated by LibScript -->
  <service name='milestone/multi-user-server' version='1' type='service'>
    <instance name='default' enabled='true'/>
  </service>
</service_bundle>
EOF
    cat << EOF > "${SYSROOT}/etc/svc/profile/services.conf"
# SMF services activated at first boot
DEFAULT_MILESTONE="${MILESTONE}"
ENABLED_SERVICES="${SERVICES}"
EOF
    ;;

  runit)
    # Runit process supervisor on illumos
    mkdir -p "${SYSROOT}/etc/runit" "${SYSROOT}/service" "${SYSROOT}/var/service"
    cat << 'EOF' > "${SYSROOT}/etc/runit/1"
#!/bin/sh
# Stage 1: system initialization
PATH=/usr/bin:/usr/sbin:/sbin
export PATH
/lib/svc/bin/restore_fs 2>/dev/null || true
touch /etc/runit/stopit
chmod 0 /etc/runit/stopit
EOF
    chmod +x "${SYSROOT}/etc/runit/1" 2>/dev/null || true

    cat << 'EOF' > "${SYSROOT}/etc/runit/2"
#!/bin/sh
# Stage 2: service supervision
PATH=/usr/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin
export PATH
exec env - PATH=$PATH runsvdir -P /service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
EOF
    chmod +x "${SYSROOT}/etc/runit/2" 2>/dev/null || true

    cat << 'EOF' > "${SYSROOT}/etc/runit/3"
#!/bin/sh
# Stage 3: system shutdown
PATH=/usr/bin:/usr/sbin:/sbin
export PATH
rx -f /etc/runit/stopit
EOF
    chmod +x "${SYSROOT}/etc/runit/3" 2>/dev/null || true

    printf 'init_path="/usr/local/sbin/runit-init:/sbin/init"
' >> "${SYSROOT}/boot/loader.conf"
    ;;

  s6)
    # s6 supervision suite
    mkdir -p "${SYSROOT}/etc/s6" "${SYSROOT}/etc/s6/scan"
    printf 'init_path="/usr/local/bin/s6-svscanboot:/sbin/init"
' >> "${SYSROOT}/boot/loader.conf"
    ;;

  dinit)
    # dinit service manager
    mkdir -p "${SYSROOT}/etc/dinit.d"
    printf 'init_path="/usr/local/sbin/dinit:/sbin/init"
' >> "${SYSROOT}/boot/loader.conf"
    ;;

  inittab-sysv)
    # Traditional /etc/inittab
    cat << 'EOF' > "${SYSROOT}/etc/inittab"
# Traditional /etc/inittab (managed by LibScript)
fs::sysinit:/sbin/bcheckrc >/dev/msglog 2>&1
is:3:initdefault:
p3:s1234:powerfail:/usr/sbin/shutdown -y -i0 -g0 >/dev/msglog 2>&1
s0:0:wait:/sbin/rc0 off >/dev/msglog 2>&1
s1:1:wait:/sbin/rc1 >/dev/msglog 2>&1
s2:2:wait:/sbin/rc2 >/dev/msglog 2>&1
s3:3:wait:/sbin/rc3 >/dev/msglog 2>&1
EOF
    ;;

  *)
    printf '[WARN]     Unknown init provider: %s, falling back to SMF
' "${PROVIDER}" >&2
    ;;
esac

date -u +"%Y-%m-%dT%H:%M:%SZ" > "${STAMP_FILE}.tmp"
mv "${STAMP_FILE}.tmp" "${STAMP_FILE}"

printf '[OK]       illumos init provider %s configured: %s
' "${PROVIDER}" "${SYSROOT}"
