# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12.9"
  config.vm.box_version = "202502.21.0"

  config.vm.synced_folder "../../gen", "/opt/repos/libscript"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :vmware_desktop do |vmware|
      vmware.vmx["ethernet0.pcislotnumber"] = "160"
      vmware.gui = false
  #   vmware.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -qq
     apt-get install -y rsync jq curl gettext-base pandoc libarchive-zip-perl
     printf '%s' 'LIBSCRIPT_ROOT_DIR='"'"'/opt/repos/libscript'"'" >> /etc/environment
  SHELL
end
