# -*- mode: ruby -*-
# vi: set ft=ruby :

# ## Overview
# Configuration and definition file for Vagrantfile.
#
# ## Usage
# Processed automatically during build or runtime.


test_target = ENV['LIBSCRIPT_TEST_TARGET'] || 'sqlite'
repo_root = ENV['LIBSCRIPT_REPO_ROOT'] || "../.."

vm_name = "freebsd-test-#{test_target}"

Vagrant.configure("2") do |config|
  config.vm.define vm_name do |t|
    t.vm.box = "bento/freebsd-15.1"
    t.vm.box_version = "0"

    t.ssh.username = "vagrant"
    t.ssh.insert_key = false
    t.ssh.private_key_path = [
      File.expand_path("~/.vagrant.d/insecure_private_keys/vagrant.key.ed25519"),
      File.expand_path("~/.vagrant.d/insecure_private_key")
    ]
    t.ssh.shell = "/bin/sh"

    t.vm.provider "qemu" do |qe|
      qe.net_mode = :user
      qe.net_device = "virtio-net-pci"
      qe.firmware_format = nil
      bios_candidates = [
        ENV["QEMU_EDK2_CODE"],
        "/opt/homebrew/share/qemu/edk2-aarch64-code.fd",
        "/usr/share/qemu/edk2-aarch64-code.fd",
        "/usr/share/edk2/aarch64/QEMU_EFI.fd"
      ].compact
      bios_path = bios_candidates.find { |path| File.exist?(path) }
      qe.extra_qemu_args = ["-bios", bios_path] if bios_path
      qe.ssh_auto_correct = true
      qe.ssh_port = 50022 + rand(1000)
      qe.memory = "4G"
      qe.smp = "2"
    end

    t.vm.allowed_synced_folder_types = [:rsync]

    t.vm.synced_folder repo_root, "/opt/repos/libscript", type: "rsync",
      rsync_exclude: [".git/", "tests_tmp/", "vagrant/"]

    t.vm.provision "shell", inline: <<-SHELL
      set -e
      export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

      echo "Updating pkg and installing prerequisites..."
      env ASSUME_ALWAYS_YES=YES pkg update
      env ASSUME_ALWAYS_YES=YES pkg install -y curl rsync jq bash

      echo "Configuring libscript..."
      export LIBSCRIPT_ROOT_DIR=/opt/repos/libscript

      echo "Installing #{test_target} using libscript..."
      /opt/repos/libscript/libscript.sh install #{test_target}

      echo "Running test for #{test_target}..."
      /opt/repos/libscript/libscript.sh test #{test_target}
    SHELL
  end
end
