# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 4
BOX_IMAGE = "bento/debian-12.9"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE
  config.vm.box_version = "202502.21.0"

  config.vm.define "jump" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "jump"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
  end

  config.vm.define "server" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "server"
    subconfig.vm.network :private_network, ip: "10.0.0.11"
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i - 1}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i - 1}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 11}"
    end
  end

  config.vm.synced_folder "../../gen", "/opt/repos/libscript"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :vmware_desktop do |vmware|
      vmware.vmx["ethernet0.pcislotnumber"] = "160"
      vmware.gui = false
  #   vmware.memory = "1024"
  end
  config.vm.provision "shell", path: "./init.sh", env: { 'NODE_COUNT' => NODE_COUNT }
  config.vm.provision "file", source: File.join("vagrant_ssh", "id_rsa"), destination: "/home/vagrant/.ssh/id_rsa"
  public_key = File.read(File.join("vagrant_ssh", "id_rsa.pub"))
  config.vm.provision :shell, :inline => "
       echo 'Copying ansible-vm public SSH Keys to the VM'
       [ -d /home/vagrant/.ssh ] || mkdir -p /home/vagrant/.ssh
       chmod 700 /home/vagrant/.ssh
       echo '#{public_key}' >> /home/vagrant/.ssh/authorized_keys
       chmod -R 600 /home/vagrant/.ssh/authorized_keys
       [ -f /home/vagrant/.ssh/config ] && mv /home/vagrant/.ssh/config /home/vagrant/.ssh/config.old
       {
         printf '%s\t%s\t%s\n' '10.0.0.10' 'jump.kubernetes.local' 'jump'
         printf '%s\t%s\t%s\n' '10.0.0.11' 'server.kubernetes.local' 'server'
         printf '%s\t%s\t%s\n' '10.0.0.12' 'node0.kubernetes.local' 'node0'
         printf '%s\t%s\t%s\n' '10.0.0.13' 'node1.kubernetes.local' 'node1'
         printf '%s\t%s\t%s\n' '10.0.0.14' 'node2.kubernetes.local' 'node2'
         printf '%s\t%s\t%s\n' '10.0.0.15' 'node3.kubernetes.local' 'node3'
       } | sudo tee -a /etc/hosts >/dev/null
       printf 'Host 10.0.*.*
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null

Host jump
  HostName 10.0.0.10
  User root
  IdentityFile /home/vagrant/.ssh/id_rsa
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null

Host server
  HostName 10.0.0.11
  User root
  IdentityFile /home/vagrant/.ssh/id_rsa
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null

Host node0
  HostName 10.0.0.12
  User root
  IdentityFile /home/vagrant/.ssh/id_rsa
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null

Host node1
  HostName 10.0.0.13
  User root
  IdentityFile /home/vagrant/.ssh/id_rsa
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null

Host node2
  HostName 10.0.0.14
  User root
  IdentityFile /home/vagrant/.ssh/id_rsa
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null

Host node3
  HostName 10.0.0.15
  User root
  IdentityFile /home/vagrant/.ssh/id_rsa
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
 ' > /home/vagrant/.ssh/config
   chmod -R 600 /home/vagrant/.ssh/config
   chown -R vagrant:vagrant /home/vagrant/.ssh
install -m 0600 -o 'root' -- /home/vagrant/.ssh/authorized_keys /root/.ssh/authorized_keys
systemctl restart sshd", privileged: true
end
