#!/bin/sh
# ## Overview
# Synthesizes Alpine-compatible APK binary packages (.apk) directly from
# component staging directories or manifests, generating .PKGINFO metadata
# and POSIX tar archive streams.
#
# ## Usage
# ./_lib/orchestration/packagers/build_apk.sh <pkg_name> <pkg_version> <staging_dir> [out_dir]

set -feu

if [ "${SCRIPT_NAME-}" ]; then
  THIS_FILE="${SCRIPT_NAME}"
elif [ "${BASH_SOURCE-}" ]; then
  THIS_FILE="${BASH_SOURCE}"
else
  THIS_FILE="${0}"
fi

case "${STACK+x}" in
  *':'"${THIS_FILE}"':'*)
    printf '[STOP]     processing "%s"
' "${THIS_FILE}" >&2
    if (return 0 2>/dev/null); then return; else exit 0; fi ;;
  *) printf '[CONTINUE] processing "%s"
' "${THIS_FILE}" >&2 ;;
esac
export STACK="${STACK:-}${THIS_FILE}"':'
SCRIPT_DIR=$(cd -- "$(dirname -- "${THIS_FILE}")" && pwd)
: "${LIBSCRIPT_ROOT_DIR:=$(d="$SCRIPT_DIR"; while [ ! -f "$d/libscript.sh" ]; do n="${d%/*}"; [ -z "$n" ] && n="/"; [ "$d" = "$n" ] && break; d="$n"; done; printf '%s
' "$d")}"
export LIBSCRIPT_ROOT_DIR

PKG_NAME="${1:-sample-pkg}"
PKG_VER="${2:-1.0.0}"
STAGE_DIR="${3:-${LIBSCRIPT_ROOT_DIR}/build/stage_apk}"
OUT_DIR="${4:-${LIBSCRIPT_ROOT_DIR}/build/packages/apk}"

mkdir -p "$OUT_DIR"
TARGET_APK="${OUT_DIR}/${PKG_NAME}-${PKG_VER}.apk"

if [ -f "$TARGET_APK" ]; then
  printf '[IDEMPOTENT] Target APK already exists: %s
' "$TARGET_APK"
  exit 0
fi

printf '[BUILD-APK] Building APK package %s version %s...
' "$PKG_NAME" "$PKG_VER"

WORK_DIR="${LIBSCRIPT_ROOT_DIR}/build/tmp_apk_${PKG_NAME}"
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR/pkg"

if [ -d "$STAGE_DIR" ]; then
  cp -R "$STAGE_DIR"/* "$WORK_DIR/pkg/" 2>/dev/null || true
else
  mkdir -p "$WORK_DIR/pkg/usr/bin"
  printf '#!/bin/sh
echo "%s %s"
' "$PKG_NAME" "$PKG_VER" > "$WORK_DIR/pkg/usr/bin/$PKG_NAME"
  chmod 755 "$WORK_DIR/pkg/usr/bin/$PKG_NAME"
fi

# Generate .PKGINFO
PKG_SIZE=$(du -sb "$WORK_DIR/pkg" 2>/dev/null | cut -f1 || du -sk "$WORK_DIR/pkg" 2>/dev/null | awk '{print $1 * 1024}' || echo 4096)
BUILD_DATE=$(date +%s 2>/dev/null || echo 1700000000)

cat <<EOF > "$WORK_DIR/.PKGINFO"
# Generated by LibScript APK Builder
pkgname = ${PKG_NAME}
pkgver = ${PKG_VER}
pkgdesc = ${PKG_NAME} packaged by LibScript
url = https://github.com/libscript/libscript
builddate = ${BUILD_DATE}
packager = LibScript OS Synthesizer <libscript@local>
size = ${PKG_SIZE}
arch = x86_64
license = MIT
depend = 
provides = ${PKG_NAME}=${PKG_VER}
EOF

# Package into .apk (tar stream)
(
  cd "$WORK_DIR"
  tar -czf "$TARGET_APK" .PKGINFO -C "$WORK_DIR/pkg" . 2>/dev/null || tar -cf - .PKGINFO -C "$WORK_DIR/pkg" . | gzip -9 > "$TARGET_APK"
)

rm -rf "$WORK_DIR"

printf '[OK] APK package generated successfully: %s
' "$TARGET_APK"
exit 0
