# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.box_version = "9.5.20241203"

  config.vm.synced_folder "../../gen", "/opt/repos/libscript"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :vmware_desktop do |vmware|
      vmware.vmx["ethernet0.pcislotnumber"] = "160"
      vmware.gui = false
  #   vmware.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
     printf '%s\n' \
       'LANG='"'"'C.UTF-8'"'"'' \
       'LC_ALL='"'"'C.UTF-8'"'"'' \
       'LIBSCRIPT_ROOT_DIR='"'"'/opt/repos/libscript'"'" >> /etc/environment
     printf 'export %s\n' \
       'LANG='"'"'C.UTF-8'"'"'' \
       'LC_ALL='"'"'C.UTF-8'"'"'' >> /home/*/.bashrc
     printf '%s\n' 'C.UTF-8 UTF-8' >> /etc/locale.gen
     printf '%s\n' 'LANG='"'"'C.UTF-8'"'" >> /etc/locale.conf
     dnf -y install git rsync jq gettext curl
  SHELL
end
