#!/bin/sh
# ## Overview
# Concurrent Multi-OS Co-Installation Orchestrator for Linux and FreeBSD.
# Deploys Linux base and FreeBSD base concurrently onto two separate target partitions
# of the same storage device, configures a shared EFI System Partition (ESP), and synthesizes
# a unified dual-boot GRUB bootloader menu with automatic FreeBSD chainloading.
#
# ## Usage
# Execute this script with target device and partition paths:
#   ./_lib/package-managers/msi-rs/distro_installers/coinstall_dual_os.sh <disk_dev> <linux_part> <freebsd_part> [esp_part]

set -feu

if [ "${SCRIPT_NAME-}" ]; then
  THIS_FILE="${SCRIPT_NAME}"
elif [ "${BASH_SOURCE-}" ]; then
  THIS_FILE="${BASH_SOURCE}"
else
  THIS_FILE="${0}"
fi

case "${STACK+x}" in
  *':'"${THIS_FILE}"':'*)
    printf '[STOP]     processing "%s"
' "${THIS_FILE}" >&2
    if (return 0 2>/dev/null); then return; else exit 0; fi ;;
  *) printf '[CONTINUE] processing "%s"
' "${THIS_FILE}" >&2 ;;
esac
export STACK="${STACK:-}${THIS_FILE}"':'
SCRIPT_DIR=$(cd -- "$(dirname -- "${THIS_FILE}")" && pwd)
: "${LIBSCRIPT_ROOT_DIR:=$(d="$SCRIPT_DIR"; while [ ! -f "$d/libscript.sh" ]; do n="${d%/*}"; [ -z "$n" ] && n="/"; [ "$d" = "$n" ] && break; d="$n"; done; printf '%s
' "$d")}"
REPO_ROOT="${LIBSCRIPT_ROOT_DIR}"

DISK_DEV="${1:-}"
LINUX_PART="${2:-}"
FREEBSD_PART="${3:-}"
ESP_PART="${4:-}"

# ## show_help
# Displays usage instructions and supported parameters.
show_help() {
  printf '%s
' "Usage: $(basename "$THIS_FILE") <disk_dev> <linux_part> <freebsd_part> [esp_part]"
  printf '%s
' "Concurrently deploys Linux and FreeBSD to separate partitions with dual-boot GRUB."
  printf '
'
  printf '%s
' "Options:"
  printf '%s
' "  --help, -h, /?, -?  Show this help message."
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ] || [ "${1:-}" = "/?" ] || [ "${1:-}" = "-?" ]; then
  show_help
  exit 0
fi

if [ -z "$DISK_DEV" ] || [ -z "$LINUX_PART" ] || [ -z "$FREEBSD_PART" ]; then
  printf '[ERROR] Disk device, Linux partition, and FreeBSD partition are all required.
' >&2
  show_help
  exit 1
fi

STAMP_FILE="/mnt/target/.coinstall_complete.stamp"
if [ -f "$STAMP_FILE" ]; then
  printf '[INFO] Co-installation already completed on %s. Skipping.
' "$DISK_DEV"
  exit 0
fi

printf '[COINSTALL] Starting Concurrent Linux + FreeBSD Dual-Boot Deployment on %s...
' "$DISK_DEV"

# 1. Format individual partitions
printf '[COINSTALL] Formatting Linux partition (%s) as ext4...
' "$LINUX_PART"
if [ -x "${REPO_ROOT}/_lib/storage/format.sh" ]; then
  "${REPO_ROOT}/_lib/storage/format.sh" "$LINUX_PART" "ext4" "linuxroot"
  printf '[COINSTALL] Formatting FreeBSD partition (%s) as UFS2...
' "$FREEBSD_PART"
  "${REPO_ROOT}/_lib/storage/format.sh" "$FREEBSD_PART" "ufs2" "freebsdroot"
fi

# 2. Mount targets
TARGET_LINUX="/mnt/target/linux"
TARGET_FREEBSD="/mnt/target/freebsd"
mkdir -p "$TARGET_LINUX" "$TARGET_FREEBSD"

if [ -x "${REPO_ROOT}/_lib/storage/mount_sysroot.sh" ]; then
  "${REPO_ROOT}/_lib/storage/mount_sysroot.sh" --mount-dual "$LINUX_PART" "$FREEBSD_PART" "$ESP_PART" 2>/dev/null || true
fi

# 3. Concurrent Installation Dispatch
printf '[COINSTALL] Concurrently installing Linux userland and FreeBSD userland...
'

# Background Job 1: Linux Base
(
  if [ -x "${SCRIPT_DIR}/install_linux.sh" ]; then
    "${SCRIPT_DIR}/install_linux.sh" "$LINUX_PART" "alpine" "$TARGET_LINUX"
  fi
) &
PID_LINUX=$!

# Background Job 2: FreeBSD Base
(
  if [ -x "${SCRIPT_DIR}/install_freebsd.sh" ]; then
    "${SCRIPT_DIR}/install_freebsd.sh" "$FREEBSD_PART" "$TARGET_FREEBSD"
  fi
) &
PID_FREEBSD=$!

# Wait for both background installations to complete
wait "$PID_LINUX"
wait "$PID_FREEBSD"

printf '[COINSTALL] Both OS userland deployments successfully finished.
'

# 4. Synthesize Dual-Boot GRUB Bootloader Configuration
printf '[COINSTALL] Configuring unified Dual-Boot GRUB menu entries...
'
GRUB_CUSTOM="${TARGET_LINUX}/etc/grub.d/40_custom"
mkdir -p "$(dirname "$GRUB_CUSTOM")"

cat << 'EOF' > "$GRUB_CUSTOM"
#!/bin/sh
exec tail -n +3 $0
# Dual-Boot configuration generated by LibScript Live Installer

menuentry "FreeBSD 15 (Native UFS2 / ZFS on Partition 4)" --class freebsd --class bsd --class os {
    insmod ufs2
    insmod zfs
    set root=(hd0,gpt4)
    chainloader /boot/loader.efi
}
EOF
chmod +x "$GRUB_CUSTOM"

# Generate GRUB configuration
if command -v grub-mkconfig >/dev/null 2>&1; then
  grub-mkconfig -o "${TARGET_LINUX}/boot/grub/grub.cfg" 2>/dev/null || true
fi

touch "$STAMP_FILE" 2>/dev/null || true
printf '[OK] Concurrent Linux + FreeBSD Dual-Boot Co-Installation completed successfully!
'
exit 0
