name: CI Tests

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.component }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      LIBSCRIPT_WINDOWS_PKG_MGR: "choco"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        component:
          - "app/_storage/celery"
          - "app/third_party/drupal"
          - "app/third_party/firecrawl"
          - "app/third_party/joomla"
          - "app/third_party/jupyterhub"
          - "app/third_party/magento"
          - "app/third_party/nextcloud"
          - "app/third_party/odoo"
          - "app/third_party/openvpn"
          - "app/third_party/phpbb"
          - "app/third_party/prestashop"
          - "app/third_party/serve-actix-diesel-auth-scaffold"
          - "app/third_party/woocommerce"
          - "app/third_party/wordpress"
          - "_lib/utilities/7zip"
          - "_lib/package-managers/apt"
          - "_lib/package-managers/dnf"
          - "_lib/package-managers/pacman"
          - "_lib/package-managers/zypper"
          - "_lib/package-managers/go"
          - "_lib/package-managers/pnpm"
          - "_lib/package-managers/yarn"
          - "_lib/package-managers/pkg"
          - "_lib/package-managers/uv"
          - "_lib/package-managers/xbps"
          - "_lib/package-managers/composer"
          - "_lib/package-managers/nuget"
          - "_lib/package-managers/helm"
          - "_lib/package-managers/asdf"
          - "_lib/package-managers/conda"
          - "_lib/package-managers/guix"
          - "_lib/package-managers/emerge"
          - "_lib/package-managers/cargo"
          - "_lib/package-managers/gem"
          - "_lib/package-managers/npm"
          - "_lib/package-managers/pip"
          - "_lib/package-managers/flatpak"
          - "_lib/package-managers/macports"
          - "_lib/toolchains/maven"
          - "_lib/package-managers/mise"
          - "_lib/package-managers/snap"
          - "_lib/package-managers/vcpkg"
          - "_lib/package-managers/apk"
          - "_lib/package-managers/brew"
          - "_lib/utilities/busybox"
          - "_lib/package-managers/pipx"
          - "_lib/package-managers/mas"
          - "_lib/package-managers/pub"
          - "_lib/package-managers/cpanm"
          - "_lib/toolchains/gradle"
          - "_lib/package-managers/pdm"
          - "_lib/package-managers/hatch"
          - "_lib/package-managers/nvm"
          - "_lib/package-managers/pyenv"

          - "_lib/package-managers/conan"
          - "_lib/package-managers/mix"
          - "_lib/package-managers/cabal"
          - "_lib/package-managers/swupd"

          - "_lib/package-managers/rustup"

          - "_lib/package-managers/choco"
          - "_lib/utilities/curl"
          - "_lib/utilities/dash"
          - "_lib/package-managers/msys2"
          - "_lib/package-managers/nix"
          - "_lib/package-managers/pkgx"
          - "_lib/utilities/powershell"
          - "_lib/package-managers/scoop"
          - "_lib/utilities/wget"
          - "_lib/package-managers/winget"
          - "_lib/git-servers"
          - "_lib/web-servers/caddy"
          - "_lib/orchestration/docker"
          - "_lib/logging/fluentbit"
          - "_lib/web-servers/httpd"
          - "_lib/web-servers/iis"
          - "_lib/orchestration/kubernetes_k0s"
          - "_lib/orchestration/kubernetes_thw"
          - "_lib/web-servers/nginx"
          - "_lib/languages/nodejs_server"
          - "_lib/security/openbao"
          - "_lib/languages/python_server"
          - "_lib/languages/rust_server"
          - "_lib/databases/etcd"
          - "_lib/databases/mariadb"
          - "_lib/databases/mongodb"
          - "_lib/databases/postgres"
          - "_lib/message-brokers/rabbitmq"
          - "_lib/databases/sqlite"
          - "_lib/caches/valkey"
          - "_lib/languages/bun"
          - "_lib/languages/c"
          - "_lib/languages/cc"
          - "_lib/languages/composer"
          - "_lib/languages/cpp"
          - "_lib/languages/csharp"
          - "_lib/languages/deno"
          - "_lib/languages/elixir"
          - "_lib/languages/go"
          - "_lib/languages/java"
          - "_lib/utilities/jq"
          - "_lib/languages/kotlin"
          - "_lib/languages/nodejs"
          - "_lib/languages/php"
          - "_lib/languages/python"
          - "_lib/languages/ruby"
          - "_lib/languages/rust"
          - "_lib/languages/sh"
          - "_lib/languages/swift"
          - "_lib/utilities/wait4x"
          - "_lib/languages/zig"
        exclude:
          - os: macos-latest
            component: "_lib/package-managers/swupd"
          - os: windows-latest
            component: "_lib/package-managers/swupd"

          - os: ubuntu-latest
            component: "_lib/package-managers/mas"
          - os: windows-latest
            component: "_lib/package-managers/mas"

          - os: windows-latest
            component: "_lib/package-managers/conda"
          - os: windows-latest
            component: "_lib/package-managers/guix"
          - os: macos-latest
            component: "_lib/package-managers/guix"
          - os: windows-latest
            component: "_lib/package-managers/asdf"
          - os: windows-latest
            component: "_lib/package-managers/pkg"
          - os: macos-latest
            component: "_lib/package-managers/pkg"
          - os: ubuntu-latest
            component: "_lib/package-managers/pkg"
          - os: windows-latest
            component: "_lib/package-managers/xbps"
          - os: macos-latest
            component: "_lib/package-managers/xbps"
          - os: ubuntu-latest
            component: "_lib/package-managers/xbps"
          - os: windows-latest
            component: "_lib/package-managers/emerge"
          - os: macos-latest
            component: "_lib/package-managers/emerge"
          - os: ubuntu-latest
            component: "_lib/package-managers/emerge"

          - os: ubuntu-latest
            component: "_lib/caches/valkey"
          - os: macos-latest
            component: "_lib/package-managers/apk"
          - os: macos-latest
            component: "_lib/package-managers/apt"
          - os: windows-latest
            component: "_lib/package-managers/apt"
          - os: macos-latest
            component: "_lib/package-managers/dnf"
          - os: windows-latest
            component: "_lib/package-managers/dnf"
          - os: macos-latest
            component: "_lib/package-managers/pacman"
          - os: windows-latest
            component: "_lib/package-managers/pacman"
          - os: macos-latest
            component: "_lib/package-managers/zypper"
          - os: windows-latest
            component: "_lib/package-managers/zypper"
          - os: macos-latest
            component: "_lib/package-managers/flatpak"
          - os: windows-latest
            component: "_lib/package-managers/flatpak"
          - os: macos-latest
            component: "_lib/package-managers/snap"
          - os: windows-latest
            component: "_lib/package-managers/snap"
          - os: ubuntu-latest
            component: "_lib/package-managers/macports"
          - os: windows-latest
            component: "_lib/package-managers/macports"
          - os: macos-latest
            component: "_lib/utilities/busybox"
          - os: windows-latest
            component: "_lib/web-servers/caddy"
          - os: ubuntu-latest
            component: "_lib/web-servers/iis"
          - os: macos-latest
            component: "_lib/web-servers/iis"
          - os: windows-latest
            component: "_lib/package-managers/nix"
          - os: ubuntu-latest
            component: "_lib/orchestration/kubernetes_thw"
          - os: macos-latest
            component: "_lib/orchestration/kubernetes_k0s"
          - os: macos-latest
            component: "_lib/orchestration/kubernetes_thw"
          - os: macos-latest
            component: "_lib/languages/rust_server"
          - os: windows-latest
            component: "_lib/orchestration/kubernetes_k0s"
          - os: windows-latest
            component: "_lib/orchestration/kubernetes_thw"
          - os: windows-latest
            component: "_lib/web-servers/nginx"
          - os: windows-latest
            component: "_lib/databases/postgres"
          - os: windows-latest
            component: "_lib/message-brokers/rabbitmq"
          - os: windows-latest
            component: "_lib/databases/etcd"
          - os: windows-latest
            component: "app/third_party/jupyterhub"
          - os: windows-latest
            component: "app/third_party/serve-actix-diesel-auth-scaffold"
          - os: windows-latest
            component: "app/third_party/firecrawl"
          - os: windows-latest
            component: "app/third_party/openvpn"
          - os: windows-latest
            component: "app/_storage/celery"
          - os: ubuntu-latest
            component: "_lib/security/openbao"
          - os: ubuntu-latest
            component: "app/third_party/wordpress"
          - os: macos-latest
            component: "app/third_party/wordpress"
          - os: macos-latest
            component: "app/third_party/serve-actix-diesel-auth-scaffold"
          - os: macos-latest
            component: "_lib/orchestration/docker"
          - os: windows-latest
            component: "app/third_party/wordpress"

    steps:
      - uses: actions/checkout@v4

      - name: Setup & Test (Unix)
        if: runner.os != 'Windows'
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          export PATH="/snap/bin:/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.bun/bin:$HOME/.deno/bin:/usr/local/go/bin:$PATH"

          cd ${{ matrix.component }}
          
          if [ -f "env.sh" ]; then
            source ./env.sh
          fi

          if [ -f ./setup.sh ]; then
            sh ./setup.sh 
          elif [ -f ./setup_generic.sh ]; then
            sh ./setup_generic.sh 
          fi
          
          if [ -x ./test.sh ]; then
            ./test.sh
          else
            echo "No test.sh found"
          fi

      - name: Setup & Test (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd ${{ matrix.component }}
          if exist setup.cmd ( call setup.cmd || exit /b 1 )
          if exist setup_win.ps1 ( powershell -ExecutionPolicy Bypass -File setup_win.ps1 || exit /b 1 )
          FOR /F "tokens=*" %%A IN ('powershell -NoProfile -Command "[Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' + [Environment]::GetEnvironmentVariable('Path', 'User')"') DO ( SET "PATH=%%A;%PATH%" )
          if exist test.cmd ( call test.cmd || exit /b 1 ) else ( echo "No test.cmd found" )
